#!/usr/bin/env bash
#change the localhost
cp /etc/hosts ~/hosts.new
sed -i 's/^127.0.0.1[[:space:]]\+localhost/127.0.0.2 localhost/' /etc/hosts
sed -i '/facebook.com/s/.*/8.8.8.8 facebook.com/' /etc/hosts
sudo cp -f ~/hosts.new /etc/hosts
